### ISSUE TITLE
ErrorException: Array to string conversion

### ISSUE THREAD

**Issue by The-Compiler** [fruux/sabre-dav#762]
With [Baikal](http://baikal-server.com/), since upgrading to PHP 7 (I think), my calendar doesn't sync anymore, and I got this in my client:

```
ErrorException: Array to string conversion in /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/CalendarQueryValidator.php:62

Stack trace:
#0 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/CalendarQueryValidator.php(62): Baikal\Framework::exception_error_handler(8, 'Array to string...', '/usr/share/weba...', 62, Array)
#1 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/CalendarQueryValidator.php(41): Sabre\CalDAV\CalendarQueryValidator->validateCompFilters(Object(Sabre\VObject\Component\VCalendar), Array)
#2 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/Backend/AbstractBackend.php(150): Sabre\CalDAV\CalendarQueryValidator->validate(Object(Sabre\VObject\Component\VCalendar), Array)
#3 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/Backend/PDO.php(680): Sabre\CalDAV\Backend\AbstractBackend->validateFilterForObject(Array, Array)
#4 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/Calendar.php(372): Sabre\CalDAV\Backend\PDO->calendarQuery('1', Array)
#5 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/Plugin.php(591): Sabre\CalDAV\Calendar->calendarQuery(Array)
#6 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/CalDAV/Plugin.php(265): Sabre\CalDAV\Plugin->calendarQueryReport(Object(DOMDocument))
#7 [internal function]: Sabre\CalDAV\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars/me@th...')
#8 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#9 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1063): Sabre\DAV\Server->broadcastEvent('report', Array)
#10 [internal function]: Sabre\DAV\Server->httpReport('calendars/me@th...')
#11 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'calendars/me@th...')
#12 /usr/share/webapps/baikal/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server->invokeMethod('REPORT', 'calendars/me@th...')
#13 /usr/share/webapps/baikal/Core/Frameworks/Baikal/WWWRoot/cal.php(82): Sabre\DAV\Server->exec()
#14 {main}
```

I also reported this as https://github.com/netgusto/Baikal/issues/434 - but I think it boils down to a SabreDAV issue looking at the stacktrace.

Sorry for the noise if this happens to be fixed already and Baikal's bundled version is outdated - I didn't verify that yet.

**Comment by The-Compiler** [comment]
Ah, I see this was fixed in c9f3e7d2be11872eb36873c5410bac476d815871 - sorry for the noise!
