### ISSUE TITLE
mysql components column is too small to hold "VEVENT,VJOURNAL,VTODO"

### ISSUE THREAD

**Issue by evert** [fruux/sabre-dav#805]
_From @tigerfoot on March 28, 2016 19:10_

Try to create or modify an existing calendar with adding support Notes choices

```
exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'components' at row 1' in /srv/www/vhosts/a.ioda.net/Core/Frameworks/Flake/Core/Database.php:180
Stack trace:
#0 /srv/www/vhosts/a.ioda.net/Core/Frameworks/Flake/Core/Database.php(180): PDO->query('INSERT INTO cal...')
#1 /srv/www/vhosts/a.ioda.net/Core/Frameworks/Flake/Core/Database.php(40): Flake\Core\Database->query('INSERT INTO cal...')
#2 /srv/www/vhosts/a.ioda.net/Core/Frameworks/Flake/Core/Model/Db.php(92): Flake\Core\Database->exec_INSERTquery('calendars', Array)
#3 /srv/www/vhosts/a.ioda.net/Core/Frameworks/Formal/Form.php(226): Flake\Core\Model\Db->persist()
#4 /srv/www/vhosts/a.ioda.net/Core/Frameworks/BaikalAdmin/Controller/User/Calendars.php(154): Formal\Form->execute()
#5 /srv/www/vhosts/a.ioda.net/Core/Frameworks/BaikalAdmin/Controller/User/Calendars.php(46): BaikalAdmin\Controller\User\Calendars->actionNew()
#6 /srv/www/vhosts/a.ioda.net/Core/Frameworks/Flake/Core/Render/Container.php(63): BaikalAdmin\Controller\User\Calendars->execute()
#7 /srv/www/vhosts/a.ioda.net/Core/Frameworks/Flake/Controller/Page.php(83): Flake\Core\Render\Container->execute()
#8 /srv/www/vhosts/a.ioda.net/Core/Frameworks/BaikalAdmin/WWWRoot/index.php(92): Flake\Controller\Page->render()
#9 {main}```

_Copied from original issue: fruux/Baikal#519_

**Comment by evert** [comment]
Interesting. Is this upgraded from an older baikal version?

**Comment by evert** [comment]
The components column is too small to hold "VEVENT,VJOURNAL,VTODO". If you are comfortable with this, you can modify the column to have a width of 21 instead of 20. I'm making this the default.

**Comment by tigerfoot** [comment]
Thanks for the quick fix.

**Comment by staabm** [comment]
fixed via https://github.com/fruux/sabre-dav/commit/0b43a61e4fc7ef3158108829b7d133deabc5e7a9
