### ISSUE TITLE
Timeout after PROPFIND

### ISSUE THREAD

**Issue by wsdefghjk-23124** [fruux/sabre-dav#925]
I'm getting a timeout error preventing proper sync on all clients (using DAVdroid). This behaviour is limited to the hosted server, on my local server I get no such error under identical setups.

Below is DAVdroid log output

2016-12-23 14:17:41 30 [syncadapter.SyncAdapterService$SyncAdapter] Sync for com.android.calendar has been initiated
2016-12-23 14:17:41 30 [AccountSettings] Account rod has version 4, current version: 4
2016-12-23 14:17:41 30 [syncadapter.CalendarsSyncAdapterService$SyncAdapter] Updating local calendar http://{REMOVED_HOST}/html/dav.php/calendars/rod/default/ with CollectionInfo(id=10, serviceID=5, type=null, url=http://{REMOVED_HOST}/html/dav.php/calendars/rod/default/, readOnly=false, displayName=Default calendar, description=Default calendar, color=null, timeZone=null, supportsVEVENT=true, supportsVTODO=false, selected=true, confirmed=false)
2016-12-23 14:17:41 30 [syncadapter.CalendarsSyncAdapterService$SyncAdapter] Synchronizing calendar #3, URL: http://{REMOVED_HOST}/html/dav.php/calendars/rod/default/
2016-12-23 14:17:42 30 [AccountSettings] Account rod has version 4, current version: 4
2016-12-23 14:17:42 30 [syncadapter.SyncManager] Preparing synchronization
2016-12-23 14:17:42 30 [syncadapter.SyncManager] Querying capabilities
2016-12-23 14:17:42 30 [HttpClient$1] --> PROPFIND http://{REMOVED_HOST}/html/dav.php/calendars/rod/default/ http/1.1
2016-12-23 14:17:42 30 [HttpClient$1] Content-Type: application/xml; charset=utf-8
2016-12-23 14:17:42 30 [HttpClient$1] Content-Length: 227
2016-12-23 14:17:42 30 [HttpClient$1] Depth: 0
2016-12-23 14:17:42 30 [HttpClient$1] 
2016-12-23 14:17:42 30 [HttpClient$1] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><n0:getctag xmlns:n0="http://calendarserver.org/ns/" /></prop></propfind>
2016-12-23 14:17:42 30 [HttpClient$1] --> END PROPFIND (227-byte body)
2016-12-23 14:18:12 30 [HttpClient$1] <-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to {REMOVED_HOST}/{REMOVED_IP} (port 80) after 30000ms
2016-12-23 14:18:12 30 [syncadapter.SyncManager] I/O exception during sync, trying again later
EXCEPTION java.net.SocketTimeoutException: failed to connect to {REMOVED_HOST}/{REMOVED_IP} (port 80) after 30000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
	at java.net.Socket.connect(Socket.java:882)
	at okhttp3.internal.AndroidPlatform.connectSocket(AndroidPlatform.java:55)
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:185)
	at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:170)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at okhttp3.RealCall.getResponse(RealCall.java:243)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:267)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager.queryCapabilities(CalendarSyncManager.java:90)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.java:134)
	at at.bitfire.davdroid.syncadapter.CalendarsSyncAdapterService$SyncAdapter.onPerformSync(CalendarsSyncAdapterService.java:69)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

2016-12-23 14:18:12 30 [syncadapter.CalendarsSyncAdapterService$SyncAdapter] Calendar sync complete

**Comment by wsdefghjk-23124** [comment]
Closed as issue moved to other project (Baikal).
